module.exports = {
  INDEX: '/',
  NOT_FOUND: '*',
  USERS: '/users',
  USER_ID: '/user/:id',
  EDIT_USER_ID: '/user/edit/:id',
  LOGIN: '/login',
  LOGOUT: '/logout',
  ITEMS: '/items',
  ITEM_ID: '/item/:id',
  EDIT_ITEM_ID: '/item/edit/:id',
  ACCESSORIES: '/accessories',
  ACCESSORY_ID: '/accessory/:id',
  EDIT_ACCESSORY_ID: '/accessory/edit/:id',
  USER_OTP: '/otp',
  USER_RESET_PASSWORD: '/reset-password',
  TRANSACTIONS: '/transactions',
  TRANSACTION_ID: '/transaction/:id',
  EDIT_TRANSACTION_ID: '/transaction/edit/:id'
}
