module.exports = {
  USERS: "users",
  STRICT: "strictQuery",
  API: "/api/",
  V1: "v1/",
  INFO: "info",
  SERVER_LOG: "server.log",
  NETWORK_ERROR: "MongoNetworkError",
  CLOUDINARY_FOLDER: "cloudinayImages", 
  OPEN: "open", 
  ERROR: "error",  
  IMAGE: "image",
  ONE_DAY: "1d",
  TOKEN: "token",
};
